### ISSUE TITLE
Any chance to get this on rust stable? 

### ISSUE THREAD

**Issue by dignifiedquire** [zyansheep/rkyv_codec#2]
Trying to use this, and was wondering if it was possible to get this running on the latest stable compiler as well. Thank you

**Comment by zyansheep** [comment]
The current implementation uses associated type bounds which are currently still [unstable](https://github.com/rust-lang/rust/issues/52662), but there may be a way to remove them :thinking:

**Comment by zyansheep** [comment]
Fixed with release 0.3.1.

**Comment by dignifiedquire** [comment]
awesome, thank you!
